#include "backend/shared_buffer.hpp"
#include "backend/backend_guard.hpp"
#include "backend/cpu_single_thread_buffer.hpp"
#include "backend/cpu_multi_thread_buffer.hpp"
#include "backend/cuda_buffer.hpp"
//#include "backend/base.hpp"
//#include "backend/cpu_single_thread_buffer.hpp"